2019-06-25 17:12:12,176 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:44]
2019-06-25 17:12:24,852 ERROR: Exception on /edit_profile [POST] [in /Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/isaialegria/coding_projects/flask/microblog/app/routes.py", line 83, in edit_profile
    if form.validate_on_submit():
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/Users/isaialegria/coding_projects/flask/microblog/app/forms.py", line 41, in validate_username
    user = User.query.filter_by_(username=self.username.data).first()
AttributeError: 'BaseQuery' object has no attribute 'filter_by_'
2019-06-25 17:13:15,188 ERROR: Exception on /edit_profile [POST] [in /Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/isaialegria/coding_projects/flask/microblog/app/routes.py", line 83, in edit_profile
    if form.validate_on_submit():
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/Users/isaialegria/coding_projects/flask/microblog/app/forms.py", line 41, in validate_username
    user = User.query.filter_by_(username=self.username.data).first()
AttributeError: 'BaseQuery' object has no attribute 'filter_by_'
2019-06-25 17:15:01,482 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:44]
2019-06-25 19:31:31,529 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:44]
2019-06-25 19:31:56,632 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:44]
2019-06-25 19:32:03,754 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:44]
2019-06-25 20:23:39,723 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:44]
2019-06-25 20:24:30,288 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:44]
2019-06-26 11:06:07,984 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:44]
2019-06-26 11:07:32,204 ERROR: Exception on /user/eesighee [GET] [in /Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/isaialegria/coding_projects/flask/microblog/app/routes.py", line 71, in user
    return render_template('user.html', user=user, posts=posts)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/isaialegria/coding_projects/flask/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/isaialegria/coding_projects/flask/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/isaialegria/coding_projects/flask/microblog/app/templates/user.html", line 15, in block "content"
    <p><a href="{{ url_for('follow', username=user.username) }}">Follow</a></p>
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'follow' with values ['username']. Did you mean 'login' instead?
