2019-07-08 08:56:12,383 ERROR: Exception on /auth/login [GET] [in /home/eesighee/.local/lib/python2.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/eesig/Documents/GitHub/microblog/app/auth/routes.py", line 27, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/eesighee/.local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/eesighee/.local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/eesig/Documents/GitHub/microblog/app/templates/auth/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/mnt/c/Users/eesig/Documents/GitHub/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/mnt/c/Users/eesig/Documents/GitHub/microblog/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/mnt/c/Users/eesig/Documents/GitHub/microblog/app/templates/auth/login.html", line 15, in block "app_content"
    <a href="{{ url_for('reset_password_request') }}">{{ _('Click to Reset It') }}</a>
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/eesighee/.local/lib/python2.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'auth.reset_password_request' instead?
2019-07-08 08:56:33,144 INFO: Micrblog startup [in /mnt/c/Users/eesig/Documents/GitHub/microblog/app/__init__.py:70]
2019-07-08 08:56:47,429 ERROR: Exception on / [GET] [in /home/eesighee/.local/lib/python2.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/eesig/Documents/GitHub/microblog/app/main/routes.py", line 26, in index
    page, app.config['POSTS_PER_PAGE'], False)
NameError: global name 'app' is not defined
2019-07-08 08:59:40,200 INFO: Micrblog startup [in /mnt/c/Users/eesig/Documents/GitHub/microblog/app/__init__.py:70]
2019-07-08 08:59:45,338 ERROR: Exception on / [GET] [in /home/eesighee/.local/lib/python2.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/eesig/Documents/GitHub/microblog/app/main/routes.py", line 30, in index
    next_url=next_url, prev_url=prev_url)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/eesighee/.local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/eesighee/.local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/eesig/Documents/GitHub/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/mnt/c/Users/eesig/Documents/GitHub/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/mnt/c/Users/eesig/Documents/GitHub/microblog/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/mnt/c/Users/eesig/Documents/GitHub/microblog/app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/mnt/c/Users/eesig/Documents/GitHub/microblog/app/templates/_post.html", line 4, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/eesighee/.local/lib/python2.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/eesighee/.local/lib/python2.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2019-07-08 09:00:44,897 INFO: Micrblog startup [in /mnt/c/Users/eesig/Documents/GitHub/microblog/app/__init__.py:70]
